# Generated by Django 4.1.4 on 2022-12-28 15:23

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Authors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=20)),
                ('middle_initials', models.CharField(blank=True, max_length=10, null=True)),
                ('last_name', models.CharField(max_length=30)),
                ('birth_date', models.DateField(blank=True, null=True, verbose_name='Born')),
                ('death_date', models.DateField(blank=True, null=True, verbose_name='Died')),
            ],
            options={
                'ordering': ['last_name', 'first_name', 'birth_date'],
            },
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('title', models.CharField(help_text='The title of the book', max_length=200)),
                ('pub_date', models.DateField(help_text='The publication date')),
                ('summary', models.CharField(help_text="A summary of the book's content", max_length=1000)),
                ('isbn', models.CharField(help_text='The ISBN number of the book', max_length=13, primary_key=True, serialize=False, unique=True, verbose_name='ISBN')),
                ('authors', models.ManyToManyField(help_text='The name(s) of the author(s)', to='catalog.authors')),
            ],
            options={
                'ordering': ['isbn', 'title'],
            },
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Enter a book genre', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=20)),
                ('middle_initials', models.CharField(blank=True, max_length=10, null=True)),
                ('last_name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='BookInstance',
            fields=[
                ('copy_id', models.UUIDField(default=uuid.uuid4, help_text="The ID of the book in the catalog's stock", primary_key=True, serialize=False)),
                ('loaned_on', models.DateTimeField(blank=True, null=True)),
                ('due_back', models.DateTimeField(blank=True, null=True)),
                ('imprint', models.CharField(max_length=200)),
                ('status', models.CharField(choices=[('m', 'Maintenance'), ('o', 'On Loan'), ('a', 'Available'), ('r', 'Reserved')], default='m', help_text='Book availability status', max_length=1)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='catalog.book')),
                ('borrower', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='catalog.user')),
            ],
            options={
                'ordering': ['due_back'],
            },
        ),
        migrations.AddField(
            model_name='book',
            name='genre',
            field=models.ManyToManyField(help_text='The genre(s) for this book', to='catalog.genre'),
        ),
        migrations.AddField(
            model_name='book',
            name='language',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.language'),
        ),
    ]
