# Generated by Django 4.1.4 on 2022-12-28 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_alter_book_isbn'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='authors',
            field=models.ManyToManyField(help_text='The name(s) of the author(s)', related_name='authors', to='catalog.author'),
        ),
        migrations.AlterField(
            model_name='book',
            name='genre',
            field=models.ManyToManyField(help_text='The genre(s) for this book', related_name='genres', to='catalog.genre'),
        ),
    ]
