# Generated by Django 4.1.4 on 2022-12-30 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_alter_book_authors_alter_book_genre'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='name_str',
            field=models.CharField(default='enter_raw_name', max_length=69),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='author',
            name='prefix',
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
        migrations.AddField(
            model_name='author',
            name='suffix',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='prefix',
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='suffix',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
    ]
