# Generated by Django 4.1.4 on 2022-12-30 16:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_author_name_str_author_prefix_author_suffix_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='author',
            old_name='name_str',
            new_name='name_match_string',
        ),
    ]
