# Generated by Django 4.1.4 on 2022-12-30 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0007_rename_name_str_author_name_match_string'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='author',
            name='name_match_string',
        ),
        migrations.AddField(
            model_name='author',
            name='name',
            field=models.CharField(default='enter_match_name', max_length=69, verbose_name='search match string'),
            preserve_default=False,
        ),
    ]
