# Generated by Django 4.1.4 on 2022-12-31 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0008_remove_author_name_match_string_author_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='author',
            name='middle_initials',
        ),
        migrations.AddField(
            model_name='author',
            name='middle_names',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
