# Generated by Django 4.1.4 on 2022-12-31 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0009_remove_author_middle_initials_author_middle_names'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='book',
            options={'ordering': ['title']},
        ),
        migrations.AlterField(
            model_name='book',
            name='authors',
            field=models.ManyToManyField(help_text='The name(s) of the author(s)', related_name='books', to='catalog.author'),
        ),
        migrations.AlterField(
            model_name='book',
            name='genre',
            field=models.ManyToManyField(help_text='The genre(s) for this book', related_name='books', to='catalog.genre'),
        ),
    ]
