# Generated by Django 4.1.4 on 2022-12-31 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0010_alter_book_options_alter_book_authors_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='summary',
            field=models.CharField(help_text="A summary of the book's content", max_length=2000),
        ),
    ]
