# Generated by Django 4.1.4 on 2023-01-24 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0015_alter_bookinstance_imprint'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='pub_date',
            field=models.DateField(blank=True, help_text='The publication date', null=True),
        ),
        migrations.AlterField(
            model_name='bookinstance',
            name='imprint',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
    ]
